# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3.4.0
_src_path: gh:epics-containers/ioc-template
description: ''
git_platform: github.com
github_org: epics-containers
name: ioc-tetramm
repo_uri: git@github.com:epics-containers/ioc-tetramm.git
rtems: false
