# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.4.3
_src_path: https://github.com/epics-containers/ioc-template
description: Support for CAENels Picoammeters
git_platform: github.com
github_org: epics-containers
name: ioc-tetramm
repo_uri: git@github.com:epics-containers/ioc-tetramm.git
rtems: false
